obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.3725, -0.49], [-0.3725, 0.49], [0.3725, 0.49], [0.3725, -0.49]]
#robot_radius: ir_of_robot
inflation_radius: 0.55

observation_sources: laser_scan_sensor #point_cloud_sensor

laser_scan_sensor: {sensor_frame: base_frame, data_type: LaserScan, topic: /ouster/scan, marking: true, clearing: true}

transform_tolerance: 1.0
global_frame: map
#point_cloud_sensor: {sensor_frame: frame_name, data_type: PointCloud, topic: /pointcloud, marking: true, clearing: true}
